- alias: 'Rule 1 xmas morning on'
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: 
      - group.all_switches
- alias: 'Rule 1 xmas morning off'
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:45:00'
  action:
    service: homeassistant.turn_off
    entity_id: 
      - group.all_switches
- alias: 'Rule 2 xmas evening on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:45:00'
  action:
    service: homeassistant.turn_on
    entity_id: 
      - group.all_switches
- alias: 'Rule 2 xmas evening off'
  trigger:
    - platform: time
      at: '22:15:00'
  action:
    service: homeassistant.turn_off
    entity_id: 
      - group.all_switches